/* Generated by Yosys 0.56 (git sha1 9c447ad9d4b1ea589369364eea38b4d70da2c599, clang++ 17.0.0 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "gray_code_unit.sv:1.1-22.10" *)
module gray_code_unit(binary_in, gray_out, gray_in, binary_out);
  (* src = "gray_code_unit.sv:4.29-4.38" *)
  input [3:0] binary_in;
  wire [3:0] binary_in;
  (* src = "gray_code_unit.sv:8.30-8.40" *)
  output [3:0] binary_out;
  wire [3:0] binary_out;
  (* src = "gray_code_unit.sv:7.29-7.36" *)
  input [3:0] gray_in;
  wire [3:0] gray_in;
  (* src = "gray_code_unit.sv:5.30-5.38" *)
  output [3:0] gray_out;
  wire [3:0] gray_out;
  assign gray_out[1] = binary_in[2] ^ binary_in[1];
  assign gray_out[2] = binary_in[3] ^ binary_in[2];
  assign binary_out[0] = binary_out[1] ^ gray_in[0];
  assign binary_out[2] = gray_in[3] ^ gray_in[2];
  assign binary_out[1] = binary_out[2] ^ gray_in[1];
  assign gray_out[0] = binary_in[1] ^ binary_in[0];
  assign binary_out[3] = gray_in[3];
  assign gray_out[3] = binary_in[3];
endmodule
